<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup>
    <ExternalIncludePath>$(SolutionDir)DirectX12\private\External\DirectX;$(SolutionDir)DirectX12\private\External\Image\;$(SolutionDir)DirectX12\private\External\Imgui\;$(SolutionDir)DirectX12\private\External\Json\;$(SolutionDir)DirectX12\private\External\Audio\;$(SolutionDir)DirectX12\private\External\fbxsdk\include\;$(ExternalIncludePath)</ExternalIncludePath>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <TreatAngleIncludeAsExternal>true</TreatAngleIncludeAsExternal>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <ExternalWarningLevel>TurnOffAllWarnings</ExternalWarningLevel>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <ExternalTemplatesDiagnostics>false</ExternalTemplatesDiagnostics>
      <WarningLevel>Level4</WarningLevel>
      <AdditionalIncludeDirectories>$(SolutionDir)\DirectX12\public\Source\include\;$(ProjectDir)\Source\pch\;$(ProjectDir)\Source\include\;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <PrecompiledHeader>Use</PrecompiledHeader>
      <PrecompiledHeaderFile>pch.h</PrecompiledHeaderFile>
      <DisableAnalyzeExternal>true</DisableAnalyzeExternal>
      <ForcedIncludeFiles>pch.h</ForcedIncludeFiles>
    </ClCompile>
    <Link>
      <AdditionalLibraryDirectories>$(SolutionDir)DirectX12\private\External\fbxsdk\lib\x64\$(Configuration)</AdditionalLibraryDirectories>
      <AdditionalDependencies>%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>